### ISSUE TITLE
Example for WS2812

### ISSUE THREAD

**Issue by mirko** [msperl/rgbled-fb#2]
As far as I understand, the ws2812 is not SPI based but just some GPIO-toggling for DIN.
Could you provide an DTS example for using a single GPIO for controlling ws2812?

**Comment by msperl** [comment]
For most parts just take the example from the readme (but you may probably want to replace it with worldsemi,ws2812b,strip and add width)
Using a single gpio is not supported, as it does require to use the spi bus! This to get the timing 100% correct. it makes some assumptions and requires the correct speed: 3x the official bitrate  - each bit of data is encoded in 3 bits on the spi bus, so 2.4 MHz is required
And even there it has some extra prerequisites! Like that there transfers have to happen without gaps - the raspberry pi only supports this requirement in Dma mode, so you need to configure at least 32 led - even if you do not have them connected!

**Comment by mirko** [comment]
I just like to use this ticket to report that I managed to get it working on an OrangePi (One) which is Allwinner H3 based - even without a level-shifter but directly connected to MOSI (3.3V). Thanks!
